[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'endel/vim-github-colorscheme'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {}
  let g:lightline.active = {'left': [ ['mode', 'paste'], ['readonly'], ['gitbranch', 'relativepath', 'modified'] ]}
  let g:lightline.colorscheme = 'shirotelin'
  let g:lightline.enable = {
        \ 'statusline': 1,
        \ 'tabline': 0
        \ }
  " let g:lightline.separator = { 'left': '', 'right': '' }
  let g:lightline.subseparator = { 'left': '|', 'right': '|' }
  let g:lightline.component = {
        \ 'lineinfo': '%3l/%L:%-2c'
        \ }
  let g:lightline.component_function = {
        \ 'gitbranch': 'gitbranch#name'
        \ }
'''

[[plugins]]
repo = "itchyny/vim-gitbranch"

[[plugins]]
repo = 'yasukotelin/shirotelin'
hook_add = '''
  " for preview bat
  let $BAT_THEME='GitHub'
  " for fzf color theme
  let $FZF_DEFAULT_OPTS="--color=light"
'''
type__depth = 1

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = "sgur/vim-textobj-parameter"

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
type__depth = 1

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
  let g:vimtex_syntax_conceal_disable = 1
  let g:vimtex_quickfix_ignore_filters=["Package caption Warning"]
  let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-shell-escape',
      \ ],
      \}
  if executable('SumatraPDF')
    let g:vimtex_view_general_viewer = 'SumatraPDF'
    let g:vimtex_view_general_options
        \ = '-reuse-instance -forward-search @tex @line @pdf'
  else
    let g:vimtex_view_method = 'zathura'
    let g:vimtex_view_general_options = "-x \"nvr +%{line} %{input}\" --synctex-forward @line:0:@tex @pdf"
  endif
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'lambdalisue/guise.vim'
hook_add = '''
  let g:guise_edit_opener='vsplit'
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
  " let g:denops_server_addr = '127.0.0.1:32123' 
'''

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'
if = 'has("nvim")'

[[plugins]]
repo = 'RRethy/vim-illuminate'
lua_add = '''
require('illuminate').configure({
    delay = 800,
})
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
lua_add = '''
  require('mason').setup()
'''

[[plugins]]
repo = "vim-denops/denops-shared-server.vim"
