[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
let g:vim_markdown_conceal=0
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'kyazdani42/blue-moon'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
let g:indentLine_fileTypeExclude = ['help', 'calendar', 'denite']
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
  let g:vimtex_syntax_conceal_default = 0
  let g:vimtex_view_method = 'zathura'
  let g:vimtex_view_general_options = "-x \"nvr +%{line} %{input}\" --synctex-forward @line:0:@tex @pdf"
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = '''
#   source ~/dotfiles/nvim/plugins/coc.rc.vim
# '''

# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# build = './install.sh'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
#   source ~/dotfiles/nvim/plugins/lightline.rc.vim
# '''

