[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
  let g:vim_markdown_conceal=0
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_no_default_key_mappings = 1
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'endel/vim-github-colorscheme'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/lightline.rc.vim
  " for preview bat
  let $BAT_THEME='GitHub'
  " for fzf color theme
  let $FZF_DEFAULT_OPTS="--color=light"
'''

[[plugins]]
repo = 'yasukotelin/shirotelin'
hook_add = '''
  " for preview bat
  let $BAT_THEME='GitHub'
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '!has("nvim")'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
  let g:vimtex_syntax_conceal_disable = 1
  let g:vimtex_view_method = 'zathura'
  let g:vimtex_view_general_options = "-x \"nvr +%{line} %{input}\" --synctex-forward @line:0:@tex @pdf"
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'lambdalisue/guise.vim'
hook_add = '''
  let g:guise_edit_opener='vsplit'
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = "prabirshrestha/vim-lsp"
if = '!has("nvim")'
hook_add = '''
	let g:lsp_completion_documentation_enabled = 0
	let g:lsp_signature_help_enabled = 0
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
if = '!has("nvim")'
