[[plugins]]
repo = 'Shougo/ddu.vim'
merged = 0
hook_add = '''
  source ~/dotfiles/nvim/plugins/ddu.rc.vim
  call Ddu_setup()
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
lazy = 1
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
merged = 0

[[plugins]]
repo = 'Shougo/ddu-ui-filer'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
merged = 0

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'matsui54/ddu-source-man'

[[plugins]]
repo = 'matsui54/ddu-filter-fzy'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'

[[plugins]]
repo = 'matsui54/ddu-source-highlight'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = "gamoutatsumi/ddu-source-nvim-lsp"

[[plugins]]
repo = "4513ECHO/ddu-source-source"

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
